### ISSUE TITLE
nonLocalizedLabel is null

### ISSUE THREAD

**Issue by MarcinMoskala** [kwizzad/kwizzad-android#4]
I am getting error:

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
at com.kwizzad.api.QueryParams.addCometQueryParams(QueryParams.java:25)
at com.kwizzad.AKwizzadBase.prepare(AKwizzadBase.java:479)
at com.kwizzad.Kwizzad.prepare(Kwizzad.java:109)
at com.gamekit.gkquiz.presentation.main.kwizzad.KwizzadItemAdapter.onBindViewHolder(KwizzadItemAdapter.kt:44)
at com.gamekit.gkquiz.presentation.main.kwizzad.KwizzadItemAdapter.onBindViewHolder(KwizzadItemAdapter.kt:19)
```

Problem is that nonLocalizedLabel is null. According to [documentation](https://developer.android.com/reference/android/content/pm/PackageItemInfo.html#nonLocalizedLabel) it might be null and there should be [getApplicationLabel](https://developer.android.com/reference/android/content/pm/PackageManager.html#getApplicationLabel(android.content.pm.ApplicationInfo)) used instead.

**Comment by Thoni99** [comment]
fixed with version 2.0.2
